import type { FullConfig } from "@playwright/test";

/**
 * Global Teardown for Playwright E2E Tests
 *
 * Handles:
 * - Test result aggregation
 * - Cleanup of test data
 * - Report generation
 * - Resource cleanup
 */

async function globalTeardown(config: FullConfig) {
  console.log("🧹 Starting Playwright Global Teardown...");

  // Clean up test data
  await cleanupTestData();

  // Generate test reports
  await generateReports();

  // Cleanup authentication files
  await cleanupAuth();

  console.log("✅ Playwright Global Teardown Complete!");
}

async function cleanupTestData() {
  console.log("🗑️  Cleaning up test data...");

  // In a real application, you might:
  // - Remove test database records
  // - Delete uploaded test files
  // - Clean up test user accounts
  // - Reset test environment state

  console.log("✅ Test data cleanup complete");
}

async function generateReports() {
  console.log("📊 Generating test reports...");

  try {
    // Test results are automatically generated by Playwright reporters
    // Additional custom reporting logic can go here

    console.log("✅ Reports generated successfully");
  } catch (error) {
    console.warn("⚠️  Report generation failed:", error);
  }
}

async function cleanupAuth() {
  console.log("🔐 Cleaning up authentication files...");

  try {
    const fs = await import("fs/promises");

    // Remove auth state files
    await fs.rm("tests/e2e/auth", {
      recursive: true,
      force: true,
    });

    console.log("✅ Authentication cleanup complete");
  } catch (error) {
    console.warn("⚠️  Auth cleanup failed:", error);
  }
}

export default globalTeardown;
